%%{init: {'theme':'default'}}%%

flowchart LR

Z[Zulip]
A[Alerta]
StatsD[StatsD]
Swift[OpenStack Swift]
Graphite[GraphiteDB]
M[Metric Processor]
Grafana[Grafana Dashboard]
DB1[(SQL Database)]
DB2[(SQL Database)]
DB3[(SQL Database)]
SD[Status Dashboard]


subgraph CloudMon plugin ApiMon
    SCH[Scheduler]
    EX[Executor\n X,Y,..]
    subgraph Ansible
        style Ansible stroke:#333,stroke-width:3px;
        P[Playbook]
        SDK[Openstack SDK]
    end
end

subgraph CloudMon plugin EpMon
    E[Endpoint Monitor]

end

C[CloudMon\n plugin X,Y,..]


subgraph Backend
    A
    Z
    StatsD
    Graphite
    M
    DB1
    Swift
end


subgraph Representation layer
        Grafana
        DB2
        SD
        DB3
end

P --> |Ansible Module| SDK
A --> Z
StatsD --> Graphite
SCH --> EX
Graphite --> M
M --> SD
EX --> |stats| DB1
EX --> |Logs| Swift
EX --> P
C & SDK & E --> |metrics| StatsD
E & SCH & EX --> A
DB1 & Graphite  --> Grafana
Grafana x--x DB2
SD x--x DB3



